version: '3.8'

services:
  backend:
    build: ./mediroute-backend
    ports:
      - "8000:8000"
    env_file:
      - ./mediroute-backend/.env
    restart: always

  frontend:
    build: ./mediroute-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
